#!/bin/bash
# DESDMDashboard cronjob execution script
# based on a bash script template by Donald Petravik

# defaults -- provide them up here

# CONFIG_FILE=0


# Help can be extracted by running

printHelp () {
cat - <<EOF

DESDMDashboard cronjob submission script.
-------------------------------------------------------------------------------

Executes a python script in the right eups setup.

$ collect_cron_job path/to/config_file.cfg path/to/python_script.py


Required Arguments:
   - the path to the config file
   - the path to the python script to be executed

Optional Arguments:
   -h,    print help and exit
   -x     debugme : turn on shell tracing (e.g. set -x)

EOF
}


# option processing  $OPTARG fetches the argument

while getopts hxc: opt
do
  case "$opt" in
      h) 
          printHelp ; exit 0 ;;
      x)
          set -x ;;
#     c)
#         CONFIG_FILE=$OPTARG ;;
      $\?)
          printHelp; exit 1 ;;
  esac;
done

# get rid of processed  options:
# $* is now arguements.
shift `expr $OPTIND - 1`

# make sure we have two arguments remaining
if (( $# != 2 ))
then 
    echo
    echo
    echo "TWO ARGUMENTS (config file & python script) required!"
    echo
    printHelp;
    exit 1;
fi

CONFIG_FILE=$1
PYTHON_SCRIPT=$2

# read the config file
source $CONFIG_FILE 

# we need to source the eups setup script first
source $EUPS_HOME/desdm_eups_setup.sh

setup -r $DESDMDASHBOARD_CODE_PATH

python $PYTHON_SCRIPT 
