#!/bin/bash

# read the config file
source $1 

# we need to source the eups setup script first
source $EUPS_HOME/desdm_eups_setup.sh

# add the path of this script to the pythonpath
MY_PATH="`dirname \"$0\"`"
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"
export PYTHONPATH=$MY_PATH:$PYTHONPATH

setup desdmdashboard trunk+0

python $2
