#!/bin/bash
# DESDMDashboard cronjob execution script
# based on a bash script template by Donald Petravik

# defaults -- provide them up here

CONFIG_FILE=0


# Help can be extracted by running

printHelp () {
cat - <<EOF

DESDMDashboard cronjob submission script.
-------------------------------------------------------------------------------

Executes a python script in the right eups setup.

run a program in various modes
    ./debug.sh program
Options
   -h,    print help and exit
   -x     debugme : turn on shell tracing (e.g. set -x)

   -c     config file 
EOF
}


# option processing  $OPTARG fetches the argument

while getopts hxc: opt
do
  case "$opt" in
      h) 
          printHelp ; exit 0 ;;
      x)
          set -x ;;
      c)
          CONFIG_FILE=$OPTARG ;;
      $\?)
          printHelp; exit 1 ;;
  esac;
done

# get rid of processed  options:
# $* is now arguements.
shift `expr $OPTIND - 1`

echo 'CONFIG_FILE: '$CONFIG_FILE
echo 'OPTIND: '$*

# read the config file
source $CONFIG_FILE 

# we need to source the eups setup script first
source $EUPS_HOME/desdm_eups_setup.sh

setup -r $DESDMDASHBOARD_CODE_PATH

python $*
